config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get "home", to: "static_pages#home"

  root 'home#home'
  resources :package_requests
  resources :zips
  resources :countries
  resources :states
  resources :cities
  resources :item_statuses
  resources :item_categories
  resources :buildings
  resources :tag_types
  resources :vendors
  resources :items
  resources :item_locations
  resources :loan_histories
  resources :order_requests
  resources :package_requests
  resources :home

  devise_for :users, controllers: {registrations: "registrations"}
  resources :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :timeoutable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/building.rb
class Building < ActiveRecord::Base
  has_many :items
  validates :building_name, :building_number, :building_code,  uniqueness: true
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :zips
  belongs_to :state
  validates_presence_of :city_name
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :states
  validates_presence_of :country_name
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :loan_histories
  has_many :package_requests
  belongs_to :building
  belongs_to :tag_type
  belongs_to :vendor
  belongs_to :item_status
  belongs_to :item_category
  scope :availability, -> {where(availability: true)}

  def vendor_name
    vendor.vendor_name
  end

  def building_name
    building.building_name
  end

  def status_of_item
    item_status.availability
  end

  def type_of_tag
    tag_type.tag_type
  end

  def category
    item_category.category
  end

  def category_item_describer
    item_category.try(:category) ||  "n/a category"
  end

  def item_describer
    item_name
  end

  def yn
    availability ? 'Yes' : 'No'
  end

end

app/models/item_category.rb
class ItemCategory < ActiveRecord::Base
  has_many :items
end

app/models/item_location.rb
class ItemLocation < ActiveRecord::Base
  has_many :package_requests
  belongs_to :user

  validates_presence_of :location_type

def item_location_describer
  location_address
end

end

app/models/item_status.rb
class ItemStatus < ActiveRecord::Base
  has_many :items
end

app/models/loan_history.rb
class LoanHistory < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
end

app/models/order_request.rb
class OrderRequest < ActiveRecord::Base
  belongs_to :user
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :cities
  belongs_to :country
  validates_presence_of :state_name
end

app/models/tag_type.rb
class TagType < ActiveRecord::Base
  has_many :items
  validates_presence_of :tag_type
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :order_requests
  has_many :loan_histories
  has_many :package_requests
  has_many :item_locations

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :encrypted_password
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :items
end

app/models/zip.rb
class Zip < ActiveRecord::Base
  belongs_to :city
  validates_presence_of :zipcode
end

app/controllers/order_requests_controller.rb
class OrderRequestsController < ApplicationController
  before_action :set_order_request, only: [:show, :edit, :update, :destroy]

  # GET /order_requests
  # GET /order_requests.json
  def index
    @order_requests = OrderRequest.where(:user_id => current_user.id)
    @order_requests = if params[:order_request]
                  OrderRequest.joins(:user).where('name ILIKE ? OR order_description ILIKE ? OR order_reason ILIKE ?', "%#{params[:order_request]}%", "%#{params[:order_request]}%", "%#{params[:order_request]}%").where(:user_id => current_user.id)
               else
                 OrderRequest.where(:user_id => current_user.id)
               end
  end

  # GET /order_requests/1
  # GET /order_requests/1.json
  def show
  end

  # GET /order_requests/new
  def new
    @order_request = OrderRequest.new
  end

  # GET /order_requests/1/edit
  def edit
  end

  # POST /order_requests
  # POST /order_requests.json
  def create
    @order_request = OrderRequest.new(order_request_params)

    respond_to do |format|
      if @order_request.save
        format.html { redirect_to @order_request, notice: 'Order request was successfully created.' }
        format.json { render :show, status: :created, location: @order_request }
      else
        format.html { render :new }
        format.json { render json: @order_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /order_requests/1
  # PATCH/PUT /order_requests/1.json
  def update
    respond_to do |format|
      if @order_request.update(order_request_params)
        format.html { redirect_to @order_request, notice: 'Order request was successfully updated.' }
        format.json { render :show, status: :ok, location: @order_request }
      else
        format.html { render :edit }
        format.json { render json: @order_request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /order_requests/1
  # DELETE /order_requests/1.json
  def destroy
    @order_request.destroy
    respond_to do |format|
      format.html { redirect_to order_requests_url, notice: 'Order request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_request
      @order_request = OrderRequest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_request_params
      params.require(:order_request).permit(:user_id, :order_description, :order_reason)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/order_requests_helper.rb
module OrderRequestsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/zips_helper.rb
module ZipsHelper
end

app/views/order_requests/_form.html.erb
<%= form_for(@order_request) do |f| %>
  <% if @order_request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_request.errors.count, "error") %> prohibited this order_request from being saved:</h2>

      <ul>
      <% @order_request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.where(:name => current_user.name), :id, :name %>
  </div>
  <div class="field">
    <%= f.label :order_description %><br>
    <%= f.text_field :order_description %>
  </div>
  <div class="field">
    <%= f.label :order_reason %><br>
    <%= f.text_field :order_reason %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_requests/edit.html.erb
<h1>Editing Order Request</h1>

<%= render 'form' %>

<%= link_to 'Show', @order_request %> |
<%= link_to 'Back', order_requests_path %>

app/views/order_requests/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Order Requests</h1>
<%= form_tag(order_requests_path, method: :get) do %>
    <%= text_field_tag :order_request %>
    <%= submit_tag 'Search', name: nil %>
<% end %><br>
<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Order description</th>
      <th>Order reason</th>
    </tr>
  </thead>

  <tbody>
    <% @order_requests.each do |order_request| %>
      <tr>
        <td><%= order_request.user.name %></td>
        <td><%= order_request.order_description %></td>
        <td><%= order_request.order_reason %></td>
        <td><%= link_to 'Edit', edit_order_request_path(order_request) %></td>
        <td><%= link_to 'Delete', order_request, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order request', new_order_request_path %>

app/views/order_requests/new.html.erb
<h1>New Order Request</h1>

<%= render 'form' %>

<%= link_to 'Back', order_requests_path %>

app/views/order_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @order_request.user.name %>
</p>

<p>
  <strong>Order description:</strong>
  <%= @order_request.order_description %>
</p>

<p>
  <strong>Order reason:</strong>
  <%= @order_request.order_reason %>
</p>

<%= link_to 'Edit', edit_order_request_path(@order_request) %> |
<%= link_to 'Back', order_requests_path %>