config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get "home", to: "static_pages#home"

  root 'home#home'
  resources :package_requests
  resources :zips
  resources :countries
  resources :states
  resources :cities
  resources :item_statuses
  resources :item_categories
  resources :buildings
  resources :tag_types
  resources :vendors
  resources :items
  resources :item_locations
  resources :loan_histories
  resources :order_requests
  resources :package_requests
  resources :home

  devise_for :users, controllers: {registrations: "registrations"}
  resources :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :timeoutable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/building.rb
class Building < ActiveRecord::Base
  has_many :items
  validates :building_name, :building_number, :building_code,  uniqueness: true
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :zips
  belongs_to :state
  validates_presence_of :city_name
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :states
  validates_presence_of :country_name
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :loan_histories
  has_many :package_requests
  belongs_to :building
  belongs_to :tag_type
  belongs_to :vendor
  belongs_to :item_status
  belongs_to :item_category
  scope :availability, -> {where(availability: true)}

  def vendor_name
    vendor.vendor_name
  end

  def building_name
    building.building_name
  end

  def status_of_item
    item_status.availability
  end

  def type_of_tag
    tag_type.tag_type
  end

  def category
    item_category.category
  end

  def category_item_describer
    item_category.try(:category) ||  "n/a category"
  end

  def item_describer
    item_name
  end

  def yn
    availability ? 'Yes' : 'No'
  end

end

app/models/item_category.rb
class ItemCategory < ActiveRecord::Base
  has_many :items
end

app/models/item_location.rb
class ItemLocation < ActiveRecord::Base
  has_many :package_requests
  belongs_to :user

  validates_presence_of :location_type

def item_location_describer
  location_address
end

end

app/models/item_status.rb
class ItemStatus < ActiveRecord::Base
  has_many :items
end

app/models/loan_history.rb
class LoanHistory < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
end

app/models/order_request.rb
class OrderRequest < ActiveRecord::Base
  belongs_to :user
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :cities
  belongs_to :country
  validates_presence_of :state_name
end

app/models/tag_type.rb
class TagType < ActiveRecord::Base
  has_many :items
  validates_presence_of :tag_type
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :order_requests
  has_many :loan_histories
  has_many :package_requests
  has_many :item_locations

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :encrypted_password
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :items
end

app/models/zip.rb
class Zip < ActiveRecord::Base
  belongs_to :city
  validates_presence_of :zipcode
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/zips_helper.rb
module ZipsHelper
end

app/views/shared/_navbar.html.erb
<div id="wrapper">
  <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <a class="navbar-brand" href="/home"><img src="http://www.uh.edu/marketing/brand/graphic-standards/_img/logo-nonbeveled-interlocking-uh-red.png" width="25" height="25"></a>

    <% if user_signed_in? %>
        <ul class = "nav pull-right">
          <li><%= link_to 'Welcome, '+current_user.name, home_path %></li>
        </ul>
    <% end %>


<div class="navbar navbar-inverse navbar-fixed-left">
  <ul class="nav navbar-nav">
    <li><%= link_to 'Items', items_path, style: 'color: #cad5dd'%></li>
    <li><%= link_to 'Package Request', new_package_request_path, style: 'color: #cad5dd' %></li>
    <li><%= link_to 'Loan History', loan_histories_path, style: 'color: #cad5dd' %></li>
    <li><%= link_to 'Order Requests', order_requests_path, style: 'color: #cad5dd' %></li>
    <li><%= link_to 'Saved Locations', item_locations_path, style: 'color: #cad5dd' %></li>
    <li><%= link_to 'Admin Console', rails_admin_path, style: 'color: #cad5dd' %></li>
    <li><%= link_to "Sign Out", destroy_user_session_path, :method => 'delete', style: 'color: darkred'%></li>
  </ul>
</div>
  </nav>
</div>