config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  get "home", to: "static_pages#home"

  root 'home#home'
  resources :package_requests
  resources :zips
  resources :countries
  resources :states
  resources :cities
  resources :item_statuses
  resources :item_categories
  resources :buildings
  resources :tag_types
  resources :vendors
  resources :items
  resources :item_locations
  resources :loan_histories
  resources :order_requests
  resources :package_requests
  resources :home

  devise_for :users, controllers: {registrations: "registrations"}
  resources :users

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :timeoutable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/building.rb
class Building < ActiveRecord::Base
  has_many :items
  validates :building_name, :building_number, :building_code,  uniqueness: true
end

app/models/city.rb
class City < ActiveRecord::Base
  has_many :zips
  belongs_to :state
  validates_presence_of :city_name
end

app/models/country.rb
class Country < ActiveRecord::Base
  has_many :states
  validates_presence_of :country_name
end

app/models/item.rb
class Item < ActiveRecord::Base
  has_many :loan_histories
  has_many :package_requests
  belongs_to :building
  belongs_to :tag_type
  belongs_to :vendor
  belongs_to :item_status
  belongs_to :item_category
  scope :availability, -> {where(availability: true)}

  def vendor_name
    vendor.vendor_name
  end

  def building_name
    building.building_name
  end

  def status_of_item
    item_status.availability
  end

  def type_of_tag
    tag_type.tag_type
  end

  def category
    item_category.category
  end

  def category_item_describer
    item_category.try(:category) ||  "n/a category"
  end

  def item_describer
    item_name
  end

  def yn
    availability ? 'Yes' : 'No'
  end

end

app/models/item_category.rb
class ItemCategory < ActiveRecord::Base
  has_many :items
end

app/models/item_location.rb
class ItemLocation < ActiveRecord::Base
  has_many :package_requests
  belongs_to :user

  validates_presence_of :location_type

def item_location_describer
  location_address
end

end

app/models/item_status.rb
class ItemStatus < ActiveRecord::Base
  has_many :items
end

app/models/loan_history.rb
class LoanHistory < ActiveRecord::Base
  belongs_to :user
  belongs_to :item
end

app/models/order_request.rb
class OrderRequest < ActiveRecord::Base
  belongs_to :user
end

app/models/state.rb
class State < ActiveRecord::Base
  has_many :cities
  belongs_to :country
  validates_presence_of :state_name
end

app/models/tag_type.rb
class TagType < ActiveRecord::Base
  has_many :items
  validates_presence_of :tag_type
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :order_requests
  has_many :loan_histories
  has_many :package_requests
  has_many :item_locations

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :encrypted_password
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :items
end

app/models/zip.rb
class Zip < ActiveRecord::Base
  belongs_to :city
  validates_presence_of :zipcode
end

app/controllers/vendors_controller.rb
class VendorsController < ApplicationController
  before_action :set_vendor, only: [:show, :edit, :update, :destroy]
  before_filter :authorize_admin, only: :index

  # GET /vendors
  # GET /vendors.json
  def index
    @vendors = Vendor.all
    @vendors = if params[:vendor]
                 Vendor.where('vendor_name LIKE ? OR email LIKE ?', "%#{params[:vendor]}%", "%#{params[:vendor]}%")
               else
                 Vendor.all
               end
  end

  # GET /vendors/1
  # GET /vendors/1.json
  def show
  end

  # GET /vendors/new
  def new
    @vendor = Vendor.new
  end

  # GET /vendors/1/edit
  def edit
  end

  # POST /vendors
  # POST /vendors.json
  def create
    @vendor = Vendor.new(vendor_params)

    respond_to do |format|
      if @vendor.save
        format.html { redirect_to @vendor, notice: 'Vendor was successfully created.' }
        format.json { render :show, status: :created, location: @vendor }
      else
        format.html { render :new }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vendors/1
  # PATCH/PUT /vendors/1.json
  def update
    respond_to do |format|
      if @vendor.update(vendor_params)
        format.html { redirect_to @vendor, notice: 'Vendor was successfully updated.' }
        format.json { render :show, status: :ok, location: @vendor }
      else
        format.html { render :edit }
        format.json { render json: @vendor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vendors/1
  # DELETE /vendors/1.json
  def destroy
    @vendor.destroy
    respond_to do |format|
      format.html { redirect_to vendors_url, notice: 'Vendor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vendor
      @vendor = Vendor.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vendor_params
      params.require(:vendor).permit(:vendor_name, :email)
    end
end

app/helpers/cities_helper.rb
module CitiesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/states_helper.rb
module StatesHelper
end

app/helpers/vendors_helper.rb
module VendorsHelper
end

app/helpers/zips_helper.rb
module ZipsHelper
end

app/views/vendors/_form.html.erb
<%= form_for(@vendor) do |f| %>
  <% if @vendor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vendor.errors.count, "error") %> prohibited this vendor from being saved:</h2>

      <ul>
      <% @vendor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :vendor_name %><br>
    <%= f.text_field :vendor_name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/vendors/edit.html.erb
<h1>Editing Vendor</h1>

<%= render 'form' %>

<%= link_to 'Show', @vendor %> |
<%= link_to 'Back', vendors_path %>

app/views/vendors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Vendors</h1>
<%= form_tag(vendors_path, method: :get) do %>
    <%= text_field_tag :vendor %>
    <%= submit_tag 'Search', name: nil %>
<% end %><br>
<table>
  <thead>
    <tr>
      <th>Vendor name</th>
      <th>Email</th>
    </tr>
  </thead>

  <tbody>
    <% @vendors.each do |vendor| %>
      <tr>
        <td><%= vendor.vendor_name %></td>
        <td><%= vendor.email %></td>
        <td><%= link_to 'Show', vendor %></td>
        <td><%= link_to 'Edit', edit_vendor_path(vendor) %></td>
        <td><%= link_to 'Delete', vendor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vendor', new_vendor_path %>

app/views/vendors/new.html.erb
<h1>New Vendor</h1>

<%= render 'form' %>

<%= link_to 'Back', vendors_path %>

app/views/vendors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Vendor name:</strong>
  <%= @vendor.vendor_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @vendor.email %>
</p>

<%= link_to 'Edit', edit_vendor_path(@vendor) %> |
<%= link_to 'Back', vendors_path %>